### PR TITLE
hollowcore, active_voice, quest

### PR DESCRIPTION
**Pull request by SoftBrilliant**

### CODE REVIEW

**Comment by SoftBrilliant** [comment]
Okay, the schema is currently a bit broken rn, a byte 0xB9 somewhere in the schemas (hollowcore has 7 fucking headers lmao) can't be read. Will need to debug

**Comment by TwnKey** [comment]
> Okay, the schema is currently a bit broken rn, a byte 0xB9 somewhere in the schemas (hollowcore has 7 fucking headers lmao) can't be read. Will need to debug

The encoding problem or something else entirely like a random byte thrown in there that doesnt make sense?

**Comment by SoftBrilliant** [comment]
> > Okay, the schema is currently a bit broken rn, a byte 0xB9 somewhere in the schemas (hollowcore has 7 fucking headers lmao) can't be read. Will need to debug
> 
> The encoding problem or something else entirely like a random byte thrown in there that doesnt make sense?
> 
> I can try to look at it in Ghidra later if you want.

I think there were 2 errors. One for decoding and there ended being another that I don't remember what it was (I replaced both with data8 in the schemas for now)

**Comment by TwnKey** [comment]
Ok thanks god the whole entry is fixed length I guess. Might check what is up later

**Comment by TwnKey** [comment]
t_place:
image

1 - (size = 8 bytes), 0x2710 - Looks like a scenario flag, but could also be an ID (it doesn't seem unique) but is not read as a scena flag anywhere I could find)
2 - (size = 8 bytes, data pointed to size = until first 0 is reached) 0x3F84 - string that usually is 5 bytes long and ends with a 0.
3 - (size = 8 bytes, data pointed to size = until next multiple of 4 bytes is reached) 0x3F8A - another string (points right after the previous string null terminator)
(note: the whole sequence of strings 2 + 3 seems to need to be aligned so there might be padding 0s to ensure the next data starts at the beginning of a 4 bytes word)
4 - (size = 8 bytes, data pointed to size = 2 * (value of (5)) - 0x3F8C - the next pointer points to a sequence of 2 bytes words (written as 4 bytes)
5 - (size = 8 bytes) 0x01 - the number of 2 bytes words pointed to by 4
6 - (size = 8 bytes, 0x3F8E - data pointed to size = 2 * (value of (7)) another pointer to a number of 2 bytes words
7 - (size = 8 bytes) 0x01 - the number of 2 bytes words pointed to by 6
8 - (size = 4 bytes) 0x3F800000 - a float 
9 - (size = 8 bytes, data pointed to size = until 0 is reached) 0x3F90 - a pointer to a latin-1 (if you want) encoded array of bytes (likely should only take the values "A" and "D") terminating at 0
image

10 - (size 8 bytes, data pointed to size = until 0 is reached) 0x3F91 - UTF 8 encoded text

**Pull request merged**
